### PR TITLE
Adding more event data

### PR DESCRIPTION
**Pull request by hypery2k**
see #9 
still WIP

### CODE REVIEW

**Comment by tobilarscheid** [comment]
Hi Martin,

like your additions! One thing I am wondering about though: What does this change mean to backwards compatibility? My prometheus knowledge is a little rusty right now, but I am guessing where I had just one metric before I would now get multiple ones grouped by for example IP address? Is that correct? Not that this is an issue as such, I would just make sure to correctly bump the new version number then and state the fact in the release notes.

**Comment by hypery2k** [comment]
the old data won't have the data, but it can be easily grouped, e.g. by event_type

**Comment by tobilarscheid** [comment]
Hi Martin,

how do we proceed with this? I think if you add documentation to the readme I would be fine to merge this.

Regards,

Tobi

**Comment by hypery2k** [comment]
sure, just added the README info

**Pull request merged**
