### PR TITLE
Create jboss-cli

### PR DESCRIPTION
**Pull request by nanoq66**
For Keycloak 6.x  cli interface is the proposed way to configure. The file is setting the exporter config

### CODE REVIEW

**Comment by tobilarscheid** [comment]
Hi @msglueck,

thank you, great addition! Could you please also update the docker build and the readme.md?

**Comment by nanoq66** [comment]
Got reminded of the missing CLI documentation today!

**Comment by nanoq66** [comment]
@joyrex2001

**Comment by joyrex2001** [comment]
Looks good 👍🏻

**Review by tobilarscheid — APPROVED** [review]

**Pull request merged**
